language: python
python:
- '3.4'
- '3.5'
cache: pip
install:
- pip install nose
- pip install flake8
- pip install coveralls
script:
- nosetests -v --with-coverage --cover-package=aptos
- flake8 .
notifications:
  slack:
    secure: kWanGF3A97GVdbm/VMND/R4494KjuD4vnlCKPe2jMvIz9x+akobOjG42/YQ7pFR+KdgWzO6OGupCB1/6lApfLNzW1lzHt0U4YKe2crs4oLLPBJyUBOiXaG3I3ciNNSks/j/kFp/ebsGCDoAJBp+21rRuRAbielN1gTOH++e/z/AKdC2lpxkXVUsGuSowNgVVHAlnL6ntPTkFo/qDanzmLqxZWy6het+0CvUq5BktCV9D3v+6TP5LjAspTG9uIZLYE0XBGutlHV68lRewjyF5WKMu9s8HXX1j0FeCXR6gVSnySn8v2HcKyeL6Nsfg8Da5WkCJwGpbnF0Cvrty+bsOpNlFdjirgimFLCZTE9hLv//z11osH2fkU0r1VycD+aO51pN1xOTMrp00yTAuAXdJg+Tb2gNdtXrc906rbB8SHx4Tay6XT6IHXx7fBamnRx0fccB7xUHEw80bNmcHDMuq4+/gzMoxuzW+IfIN9HkHeviuPr7KJbsbMDhFi3feiBj4fhwDsSb6jJnjqfsNHck8iUCSfVdRh04/+u+eEA8Yuldn0kRztaVYt2KmQg1/bjWbrQR5Q9PIyN0L9kkoaisMLMhcdP0O+r+mp1QRrnfLUeFGc9JEFcrBa6Dxrh1Im2tXiH2dwVXTCauVGb5Zp4pUdRoT9jZNgIOspk8B343Du0Y=
after_success: coveralls
